CREATE TABLE noteful_notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    modified TEXT NOT NULL DEFAULT now(),
    content TEXT,
    name TEXT, 
    folderid INTEGER REFERENCES noteful_folders(id) ON DELETE CASCADE NOT NULL
);